public class ImsSearchException extends Exception {
	//private Integer errorCode;
	//private String errorMessage;

	//public ImsSearchException(Integer code, String message){
	//	errorCode = code;
	//	errorMessage = message;
	//}

	//public override String getMessage(){
	//	if(errorCode == 16){
	//		return 'Too many records found. Please refine your search filter';
	//	}

	//	return super.getMessage();
	//}
}