public with sharing class SearchResultWrapperMVN {

	public String hceId {get;set;}
	public String firstName {get;set;}
	public String lastName {get;set;}
	public String middleName {get;set;}
	public String suffix {get;set;}
	public String genderCode {get;set;}
	public String professionalDesc {get;set;}
	public String specialty {get;set;}
	public String partyId {get;set;}
	public String deaNum {get;set;}
	public String slnNum {get;set;}
	public String npiNum {get;set;}

	public String city {get;set;}
	public String state {get;set;}
	public String zip5 {get;set;}
	
	public SearchResultWrapperMVN() {
		
	}
}